const cfg=window.CH_CONFIG||{};const hasSupabase=Boolean(cfg.supabaseUrl&&cfg.supabaseAnonKey&&window.supabase);const sb=hasSupabase?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;let authMode='login';let currentUser=null;
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function scrollToEl(sel){document.querySelector(sel)?.scrollIntoView({behavior:'smooth'})}
function renderAnnouncements(items){const el=$('#announcementGrid');if(!items?.length){el.innerHTML='<div class="empty">No announcements have been published yet.</div>';return}el.innerHTML=items.map(x=>`<article class="card"><div class="date">${new Date(x.created_at).toLocaleDateString()}</div><h3>${escapeHtml(x.title)}</h3><p>${escapeHtml(x.body)}</p></article>`).join('')}
function renderEvents(items){const el=$('#eventGrid');if(!items?.length){el.innerHTML='<div class="empty">No upcoming events are scheduled.</div>';return}el.innerHTML=items.map(x=>{const d=new Date(x.starts_at);return `<article class="event"><div class="event-date"><b>${d.getDate()}</b><small>${d.toLocaleString(undefined,{month:'short'})}</small></div><div><h3>${escapeHtml(x.title)}</h3><p>${escapeHtml(x.description||'Community event')}</p><small style="color:#7f95a4">${d.toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})} · ${escapeHtml(x.location||'Community Hub')}</small></div></article>`}).join('');$('#eventStat').textContent=items.length}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function loadData(){if(!sb){renderAnnouncements([{title:'Welcome to Coastal Horizon RolePlay',body:'The Community Hub is live. Connect your account, explore departments, and watch this space for official announcements.',created_at:new Date().toISOString()},{title:'Community Hub Launch',body:'Applications, events, announcements, and member tools are being brought together in one place.',created_at:new Date().toISOString()},{title:'Grand Theft Auto Community',body:'Our community is built to grow with the future of Grand Theft Auto roleplay.',created_at:new Date().toISOString()}]);renderEvents([{title:'Community Launch Night',description:'Meet the staff, learn how Coastal Horizon works, and get ready for the next chapter.',starts_at:new Date(Date.now()+86400000*3).toISOString(),location:'Discord'}]);$('#memberStat').textContent='—';return}
 try{const [a,e,p]=await Promise.all([sb.from('announcements').select('*').eq('published',true).order('created_at',{ascending:false}).limit(6),sb.from('events').select('*').eq('published',true).gte('starts_at',new Date().toISOString()).order('starts_at').limit(6),sb.from('profiles').select('id',{count:'exact',head:true})]);if(a.error)throw a.error;renderAnnouncements(a.data);renderEvents(e.data);$('#memberStat').textContent=p.count??'—'}catch(err){console.error(err);toast('Database is not configured yet. Showing demo content.');renderAnnouncements([]);renderEvents([])}}
function updateCountdown(){const target=new Date('2026-11-19T00:00:00-05:00').getTime();let diff=Math.max(0,target-Date.now());const day=Math.floor(diff/86400000);diff%=86400000;const hr=Math.floor(diff/3600000);diff%=3600000;const min=Math.floor(diff/60000);const sec=Math.floor(diff/1000)%60;$('#days').textContent=String(day).padStart(3,'0');$('#hours').textContent=String(hr).padStart(2,'0');$('#mins').textContent=String(min).padStart(2,'0');$('#secs').textContent=String(sec).padStart(2,'0')}
function openAuth(){if(!sb){toast('Connect Supabase in config.js first.');return}$('#authModal').showModal()}
function setAuthMode(){const signup=authMode==='signup';$('#authTitle').textContent=signup?'Create account':'Sign in';$('#authSubtitle').textContent=signup?'Create your Community Hub account.':'Access applications and community tools.';$('#authSubmit').textContent=signup?'Create Account':'Sign In';$('#toggleAuth').textContent=signup?'Already have an account? Sign in':'Need an account? Create one'}
async function refreshSession(){if(!sb)return;const {data}=await sb.auth.getSession();currentUser=data.session?.user||null;$('#loginBtn').textContent=currentUser?'Account':'Sign In'}
async function authSubmit(e){e.preventDefault();if(!sb)return;const email=$('#email').value.trim(),password=$('#password').value;let result;if(authMode==='signup')result=await sb.auth.signUp({email,password});else result=await sb.auth.signInWithPassword({email,password});if(result.error){toast(result.error.message);return}toast(authMode==='signup'?'Account created. Check your email if confirmation is enabled.':'Signed in successfully.');$('#authModal').close();await refreshSession()}
async function submitApplication(e){e.preventDefault();if(!sb||!currentUser){toast('Please sign in first.');return}const {error}=await sb.from('applications').insert({user_id:currentUser.id,display_name:$('#appName').value.trim(),department:$('#appArea').value,reason:$('#appWhy').value.trim()});if(error){toast(error.message);return}$('#applicationModal').close();e.target.reset();toast('Application submitted successfully.')}
function init(){ $('#year').textContent=new Date().getFullYear();$('#discordBtn').onclick=()=>window.open(cfg.discordInvite||'#','_blank');$('#loginBtn').onclick=()=>currentUser?toast('You are signed in.') : openAuth();$('#applyBtn').onclick=()=>{if(!currentUser){openAuth();toast('Sign in to submit an application.')}else $('#applicationModal').showModal()};$('#authForm').onsubmit=authSubmit;$('#applicationForm').onsubmit=submitApplication;$('#toggleAuth').onclick=()=>{authMode=authMode==='login'?'signup':'login';setAuthMode()};$$('[data-close]').forEach(x=>x.onclick=()=>x.closest('dialog').close());$$('[data-scroll]').forEach(x=>x.onclick=()=>scrollToEl(x.dataset.scroll));$('#refreshBtn').onclick=loadData;$('#menuBtn').onclick=()=>$('.topbar').classList.toggle('mobile');setAuthMode();updateCountdown();setInterval(updateCountdown,1000);loadData();refreshSession();if(sb)sb.auth.onAuthStateChange((_e,s)=>{currentUser=s?.user||null;$('#loginBtn').textContent=currentUser?'Account':'Sign In'});}
document.addEventListener('DOMContentLoaded',init);
